We are going to start creating a series for training.

y[0] = x[0]

y[1] = x[1]

y[2] = x[0]+x[1]


We are going to create different trainning sequences with different startup variables

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.contrib import rnn

In [50]:
num_seqs=7
seq_len=30
seqs_x=np.array([]).reshape(-1,seq_len)
seqs_y=np.array([]).reshape(-1,seq_len)
for i in xrange(num_seqs):
    x=np.empty((0),dtype=np.float64)
    for j in xrange(seq_len):
        x=np.append(x,np.float64(np.random.randint(0,50)))

    y=np.empty_like(x)
    y[0]=x[0]
    y[1]=x[1]
    for j in xrange(2,len(x)):
        y[j]=x[j]+x[j-1]
    seqs_x=np.concatenate((seqs_x, np.reshape(x,(1,-1))))
    seqs_y=np.concatenate((seqs_y, np.reshape(y,(1,-1))))
    
    

print "Sequences X:"
print seqs_x
print "Sequences Y:"
print seqs_y

Sequences X:
[[ 3.  6.  2. 49. 24.  8. 40.  6. 28. 46. 33. 46. 30. 36. 24.  7. 10. 17.
   9.  2.  5. 39. 36. 37. 33. 29. 10. 33. 42. 42.]
 [43.  5. 28. 12. 35. 27. 27. 27.  0. 11. 12. 26. 36. 35. 34. 11. 40. 49.
   0. 39. 23.  9.  2. 37. 39. 38.  9.  1. 28. 22.]
 [17. 21. 38. 15.  1. 20. 12. 15. 19. 48. 43. 38. 41. 49. 21.  2. 12. 44.
  40. 27.  9. 32. 49. 16. 49. 36. 27. 26. 15. 38.]
 [49. 33. 47. 19. 35. 38. 21. 42.  9. 33. 17. 35. 11.  7. 34. 35. 32.  2.
  11. 23. 32. 30. 14. 31. 39. 23. 32. 46. 47. 29.]
 [ 0. 21. 21. 21. 32. 16. 48. 28. 20. 28. 23. 22. 41.  7. 37.  3. 44. 49.
  14. 12. 43. 19. 23. 12. 49. 16. 31. 11. 38. 10.]
 [ 8. 24. 31. 46. 48. 10. 43.  3.  4. 13. 49.  1. 35. 24. 40. 20.  0. 24.
  48. 47.  0. 17. 11. 33. 30. 16. 41. 11. 39. 23.]
 [28. 15. 17.  4. 40. 28. 34. 39. 18. 47. 23. 33. 32. 46. 19. 44. 28. 35.
  33. 17. 34. 36. 42. 47. 41.  6. 29. 16.  4. 38.]]
Sequences Y:
[[ 3.  6.  8. 51. 73. 32. 48. 46. 34. 74. 79. 79. 76. 66. 60. 31. 17. 27.
  26. 11.  7. 44. 75. 73

In [51]:
th = np.int(num_seqs*0.7)
train_x= seqs_x[:th]
test_x = seqs_x[th:]
train_y= seqs_y[:th]
test_y = seqs_y[th:]

In [52]:
lstm_size = 10
num_features = 1

In [53]:
tf.reset_default_graph()

#The input data is going to be [batch_size]
x_data = tf.placeholder(tf.float32, [None, 1],"x_data")

#The output data is going to be [batch_size, 1]
y_real = tf.placeholder(tf.float32, [None, 1],"y_real")

lstm = tf.contrib.rnn.BasicLSTMCell(lstm_size, state_is_tuple=True,name="LSTM_cell")
c_in=tf.placeholder(tf.float32, [None, lstm_size],name="c_in")
h_in=tf.placeholder(tf.float32, [None, lstm_size],name="h_in")
                    
init_state = tf.contrib.rnn.LSTMStateTuple( c=c_in, h=h_in)


# The value of state is updated after processing each batch of words.
output_rnn, out_state = lstm(x_data, init_state)

W_out = tf.get_variable("Wout",initializer=tf.random_normal([lstm_size,1]))
b_out = tf.get_variable("b_out",initializer=tf.random_normal([1]))

# The LSTM output can be used to make next word predictions
out = tf.matmul(output_rnn, W_out) + b_out

loss = tf.losses.mean_squared_error(y_real,out)
#train_op = tf.train.AdamOptimizer(learning_rate=0.0002).minimize(loss)

optimizer = tf.train.AdamOptimizer(learning_rate=0.0002)
gvs = optimizer.compute_gradients(loss)
capped_gvs = [(tf.clip_by_value(grad, -1., 1.), var) for grad, var in gvs]
train_op = optimizer.apply_gradients(capped_gvs)

sess=tf.Session()
sess.run(tf.global_variables_initializer())

# We save the graph to analyze it in Tensorboard
train_writer = tf.summary.FileWriter('./graphtf',sess.graph)

Le'ts try with an example, yust one sample from the list

In [54]:
np_c = np.zeros((1, lstm_size),np.float32)
np_h = np.zeros((1, lstm_size),np.float32)

o = sess.run([out], feed_dict={x_data: train_x[0:1,0].reshape(-1,1), 
                                      y_real:train_y[0:1,0].reshape(-1,1),
                                      c_in:np_c, h_in:np_h})

print "The estimated output without training is:"
print np.squeeze(o)
print "But it should be:"
print train_y[1,0]

The estimated output without training is:
0.17150217
But it should be:
43.0


Let's train the model

In [55]:
max_epocs=10000
for j in xrange(max_epocs):
    np_c = np.zeros((train_x.shape[0], lstm_size),np.float32)
    np_h = np.zeros((train_x.shape[0], lstm_size),np.float32)
    for i in xrange(train_x.shape[1]):        
        new_state,myloss,_ = sess.run([out_state,loss,train_op], 
               feed_dict={x_data: train_x[:,i].reshape(-1,1), 
                          y_real:train_y[:,i].reshape(-1,1),
                          c_in:np_c, h_in:np_h
                         })        
        np_c=new_state.c
        np_h=new_state.h
    if j%500 == 0:
        print myloss

4417.588
912.04236
222.94768
125.8858
57.600925
50.0817
74.85818
28.053059
7.297879
21.0089
8.8673115
13.872299
23.86504
2.0798922
2.675952
25.015575
6.814285
83.88816
39.195007
15.484887


Let's check with the known sequences

In [57]:
np_c = np.zeros((1, lstm_size),np.float32)
np_h = np.zeros((1, lstm_size),np.float32)

seq_id=0

out_seq=np.array([])
for i in xrange(test_x.shape[1]):
    out_val,new_state = sess.run([out,out_state], feed_dict={x_data: test_x[seq_id,i].reshape(-1,1),       
                                                             c_in:np_c, h_in:np_h})
    out_seq = np.append(out_seq,out_val)
    np_c=new_state.c
    np_h=new_state.h

print "The estimated output sequence is:"
print out_seq
print "The real output sequence is:"
print test_y[seq_id,:]

The estimated output sequence is:
[12.32107353 22.30460358 43.58792496 42.40033722 61.8417778  53.01939011
 56.33670044 58.39256287 45.43508148 56.55605316 54.44507599 44.94801712
 69.1426239  39.26014709 48.01186752 23.61235046 35.5365715  70.59922028
 53.08533478 25.87182236 52.11916351 55.65919113 37.14069748 41.71841049
 51.17979431 57.79838562 43.18199921 46.7674408  47.27316666 51.6287117 ]
The real output sequence is:
[ 0. 21. 42. 42. 53. 48. 64. 76. 48. 48. 51. 45. 63. 48. 44. 40. 47. 93.
 63. 26. 55. 62. 42. 35. 61. 65. 47. 42. 49. 48.]


## Sequences with N-dimensions

We are going to start creating a series for training.
\\[
\begin{align}
  y[0] &= x_0[0] \\
  y[1] &= x_0[1] \\
  y[2] &= x_0[0]+x_0[1]+x_1[2]+x_1[1]    
\end{align}
\\]



In [16]:
num_seqs=7
seq_len=15
seqs_x=np.array([]).reshape(-1,seq_len,2)
seqs_y=np.array([]).reshape(-1,seq_len)
for i in xrange(num_seqs):
    x0=np.empty((0),dtype=np.float64)
    x1=np.empty((0),dtype=np.float64)    
    for j in xrange(seq_len):
        x0=np.append(x0,np.float64(np.random.randint(0,50)))
        x1=np.append(x1,np.float64(np.random.randint(0,50)))

    y=np.empty_like(x0)
    y[0]=x0[0]
    y[1]=x0[1]
    for j in xrange(2,seq_len):
        y[j]=x0[j]+x0[j-1]+x1[j]
    x_vec=np.concatenate((np.reshape(x0,(1,-1,1)),np.reshape(x1,(1,-1,1))),axis=2)
    seqs_x=np.concatenate((seqs_x, x_vec ),axis=0)
    seqs_y=np.concatenate((seqs_y, np.reshape(y,(1,-1))))
    
    

print "Sequences X:"
print seqs_x
print "Sequences Y:"
print seqs_y

Sequences X:
[[[43. 31.]
  [27. 17.]
  [47.  0.]
  [ 0.  0.]
  [ 4. 17.]
  [13. 36.]
  [12. 45.]
  [28. 19.]
  [32. 42.]
  [32. 43.]
  [27. 17.]
  [ 1.  0.]
  [36. 38.]
  [37. 37.]
  [17. 10.]]

 [[29. 39.]
  [37. 46.]
  [38. 34.]
  [ 2. 27.]
  [37. 27.]
  [20. 46.]
  [19. 32.]
  [46. 20.]
  [19.  5.]
  [ 5. 38.]
  [ 7. 28.]
  [ 8. 41.]
  [24. 43.]
  [ 9. 14.]
  [44. 33.]]

 [[23.  3.]
  [31. 37.]
  [ 8. 37.]
  [28.  2.]
  [ 0. 35.]
  [ 0. 32.]
  [ 1. 26.]
  [34. 24.]
  [35. 39.]
  [39.  8.]
  [28. 30.]
  [26. 31.]
  [ 5. 13.]
  [45. 31.]
  [33. 34.]]

 [[38. 39.]
  [31.  9.]
  [24. 21.]
  [46. 37.]
  [46. 30.]
  [ 7. 44.]
  [10. 45.]
  [19. 25.]
  [35. 45.]
  [16. 39.]
  [37. 17.]
  [10.  9.]
  [20. 48.]
  [45. 17.]
  [31. 40.]]

 [[12. 12.]
  [43. 21.]
  [11. 15.]
  [27. 45.]
  [32. 17.]
  [ 0.  6.]
  [30. 21.]
  [39. 42.]
  [39. 15.]
  [36. 44.]
  [19. 13.]
  [ 9.  3.]
  [12. 45.]
  [ 2. 47.]
  [49. 15.]]

 [[16. 15.]
  [23. 16.]
  [ 0. 20.]
  [10. 29.]
  [38. 28.]
  [15. 37.]
  [10

In [17]:
th = np.int(num_seqs*0.7)
train_x= seqs_x[:th]
test_x = seqs_x[th:]
train_y= seqs_y[:th]
test_y = seqs_y[th:]

In [4]:
lstm_size = 10
num_features = 1

In [14]:
tf.reset_default_graph()
num_features=2

#The input data is going to be [batch_size]
x_data = tf.placeholder(tf.float32, [None, num_features],"x_data")

#The output data is going to be [batch_size, 1]
y_real = tf.placeholder(tf.float32, [None, 1],"y_real")

lstm = tf.contrib.rnn.BasicLSTMCell(lstm_size, state_is_tuple=True,name="LSTM_cell")
c_in=tf.placeholder(tf.float32, [None, lstm_size],name="c_in")
h_in=tf.placeholder(tf.float32, [None, lstm_size],name="h_in")
                    
init_state = tf.contrib.rnn.LSTMStateTuple( c=c_in, h=h_in)


# The value of state is updated after processing each batch of words.
output_rnn, out_state = lstm(x_data, init_state)

W_out = tf.get_variable("Wout",initializer=tf.random_normal([lstm_size,1]))
b_out = tf.get_variable("b_out",initializer=tf.random_normal([1]))

# The LSTM output can be used to make next word predictions
out = tf.matmul(output_rnn, W_out) + b_out

loss = tf.losses.mean_squared_error(y_real,out)
#train_op = tf.train.AdamOptimizer(learning_rate=0.0002).minimize(loss)

optimizer = tf.train.AdamOptimizer(learning_rate=0.0002)
gvs = optimizer.compute_gradients(loss)
capped_gvs = [(tf.clip_by_value(grad, -1., 1.), var) for grad, var in gvs]
train_op = optimizer.apply_gradients(capped_gvs)

sess=tf.Session()
sess.run(tf.global_variables_initializer())

# We save the graph to analyze it in Tensorboard
train_writer = tf.summary.FileWriter('./graphtf',sess.graph)

Le'ts try with an example, yust one sample from the list

In [22]:
np_c = np.zeros((1, lstm_size),np.float32)
np_h = np.zeros((1, lstm_size),np.float32)

o = sess.run([out], feed_dict={x_data: train_x[0:1,0], 
                                      y_real:train_y[0:1,0].reshape(-1,1),
                                      c_in:np_c, h_in:np_h})

print "The estimated output without training is:"
print np.squeeze(o)
print "But it should be:"
print train_y[1,0]

The estimated output without training is:
-0.2244373
But it should be:
28.0


Let's train the model

In [24]:
max_epocs=10000
for j in xrange(max_epocs):
    np_c = np.zeros((train_x.shape[0], lstm_size),np.float32)
    np_h = np.zeros((train_x.shape[0], lstm_size),np.float32)
    for i in xrange(train_x.shape[1]):        
        new_state,myloss,_ = sess.run([out_state,loss,train_op], 
               feed_dict={x_data: train_x[:,i], 
                          y_real:train_y[:,i].reshape(-1,1),
                          c_in:np_c, h_in:np_h
                         })        
        np_c=new_state.c
        np_h=new_state.h
    if j%500 == 0:
        print myloss

91.882385
86.09121
162.65552
145.52869
136.37135
115.608345
95.841606
80.55209
72.08536
45.366634
59.180256
37.831577
24.193466
98.015366
26.17407
26.645082
13.29495
3.6439674
8.933705
8.963353


In [28]:
test_x[1,1,:].shape

(2,)

In [29]:
np_c = np.zeros((1, lstm_size),np.float32)
np_h = np.zeros((1, lstm_size),np.float32)

seq_id=0

out_seq=np.array([])
for i in xrange(test_x.shape[1]):
    out_val,new_state = sess.run([out,out_state], feed_dict={x_data: test_x[seq_id,i].reshape(1,2),       
                                                             c_in:np_c, h_in:np_h})
    out_seq = np.append(out_seq,out_val)
    np_c=new_state.c
    np_h=new_state.h

print "The estimated output sequence is:"
print out_seq
print "The real output sequence is:"
print test_y[seq_id,:]

The estimated output sequence is:
[22.26746559 64.88938904 64.10012817 58.24990845]
The real output sequence is:
[21. 34. 96. 53.]


## Train more than one timestep at a time


https://www.tensorflow.org/api_docs/python/tf/nn/static_rnn

https://www.tensorflow.org/api_docs/python/tf/nn/dynamic_rnn

In [27]:
tf.reset_default_graph()
lstm_size = 10
num_features=2

#The input data is going to be [batch_size, max_time, num_features]
x_data = tf.placeholder(tf.float32, [None, None, num_features],"x_data")

#The output data is going to be [batch_size, max_time, 1]
y_real = tf.placeholder(tf.float32, [None, None],"y_real")

lstm = tf.contrib.rnn.BasicLSTMCell(lstm_size, state_is_tuple=True,name="LSTM_cell")

batch_size=tf.shape(x_data)[0]
init_state = lstm.zero_state(batch_size, dtype=tf.float32)

# input data shape: 
output_rnn, out_state = tf.nn.dynamic_rnn(lstm, x_data, initial_state=init_state, dtype=tf.float32)

W_out = tf.get_variable("Wout",initializer=tf.random_normal([lstm_size,1]))
b_out = tf.get_variable("b_out",initializer=tf.random_normal([1]))

# The LSTM output can be used to make next word predictions
W_repeated = tf.tile(tf.expand_dims(W_out,0), [batch_size,1,1])
out = tf.matmul(output_rnn, W_repeated)+b_out
out = tf.squeeze(out)


loss = tf.losses.mean_squared_error(y_real,out)
#train_op = tf.train.AdamOptimizer(learning_rate=0.0002).minimize(loss)

optimizer = tf.train.AdamOptimizer(learning_rate=0.0002)
gvs = optimizer.compute_gradients(loss)
capped_gvs = [(tf.clip_by_value(grad, -1., 1.), var) for grad, var in gvs]
train_op = optimizer.apply_gradients(capped_gvs)

sess=tf.Session()
sess.run(tf.global_variables_initializer())

# We save the graph to analyze it in Tensorboard
train_writer = tf.summary.FileWriter('./graphtf',sess.graph)

In [30]:
o = sess.run([out], feed_dict={x_data: train_x, 
                                      y_real:train_y})

print "The estimated output without training is:"
print np.squeeze(o)
print "But it should be:"
print train_y

The estimated output without training is:
[[-0.41303676 -0.40426612  0.23558635  1.2864469  -0.49936056 -0.5561915
  -0.57699656 -0.24846026 -0.3849225  -0.4438967  -0.4035074   1.0339581
  -0.44398555 -0.44611365 -0.2453152 ]
 [-0.52652174 -0.5018935  -0.4436766  -0.5889065  -0.34171748 -0.55375427
  -0.45488316 -0.3766882   0.0370422  -0.5829426  -0.56840324 -0.5856973
  -0.31232265 -0.20764083 -0.29059073]
 [ 0.0423305  -0.49548733 -0.57986057  0.29740518 -0.5950342  -0.59829366
  -0.5969884  -0.14465186 -0.27189603 -0.23082167 -0.45416546 -0.51093805
  -0.48353654 -0.38957202 -0.43532014]
 [-0.4363392  -0.2647047  -0.44771308 -0.4104626  -0.39052504 -0.5729186
  -0.5752999  -0.11805862 -0.09740436 -0.5325658  -0.34641188 -0.24376509
  -0.56210905 -0.361282   -0.47438204]]
But it should be:
[[ 43.  27.  74.  47.  21.  53.  70.  59. 102. 107.  76.  28.  75. 110.
   64.]
 [ 29.  37. 109.  67.  66. 103.  71.  85.  70.  62.  40.  56.  75.  47.
   86.]
 [ 23.  31.  76.  38.  63.  32.  27

In [36]:
max_epocs=80000
for j in xrange(max_epocs):
    myloss,_ = sess.run([loss,train_op], 
               feed_dict={x_data: train_x, 
                          y_real:train_y})     
    if j%2000 == 0:
        print myloss

84.05057
77.25895
70.48092
61.389854
54.191578
47.96619
42.475643
37.183155
33.295925
30.53872
28.356226
26.580332
25.021322
23.525457
21.861723
18.551582
9.578389
7.716349
6.204856
5.0935464


In [37]:
o = sess.run([out], feed_dict={x_data: test_x, 
                                      y_real:test_y})

print "The estimated output without training is:"
print np.squeeze(o)
print "But it should be:"
print train_y

The estimated output without training is:
[[ 28.157497  24.816872  97.85834  103.21746   72.35114   36.783173
   38.754852  60.181187  98.09556  110.00153   72.358116  39.98977
   71.943886  57.214634  68.17764 ]
 [ 31.37629   14.589729  57.650955  51.52385   83.423805  99.51031
   57.50415   36.90095   87.96876   44.491516  64.98362   52.612328
   56.011658  53.9407    74.93728 ]
 [ 46.861237  28.572872  96.64514   38.53342   66.94159   50.173164
   49.522614  45.25449   65.305405  88.7134    87.1785   108.53193
  100.234795  33.81314   79.44018 ]]
But it should be:
[[ 43.  27.  74.  47.  21.  53.  70.  59. 102. 107.  76.  28.  75. 110.
   64.]
 [ 29.  37. 109.  67.  66. 103.  71.  85.  70.  62.  40.  56.  75.  47.
   86.]
 [ 23.  31.  76.  38.  63.  32.  27.  59. 108.  82.  97.  85.  44.  81.
  112.]
 [ 38.  31.  76. 107. 122.  97.  62.  54.  99.  90.  70.  56.  78.  82.
  116.]]


## Several layers and dropout

In [60]:
tf.reset_default_graph()
lstm_size1 = 30
lstm_size2 = 5
drop_out=0.1
num_features=2

#The input data is going to be [batch_size, max_time, num_features]
x_data = tf.placeholder(tf.float32, [None, None, num_features],"x_data")
#The output data is going to be [batch_size, max_time, 1]
y_real = tf.placeholder(tf.float32, [None, None],"y_real")

lstm_layer1 = tf.contrib.rnn.BasicLSTMCell(lstm_size1, state_is_tuple=True,name="LSTM_layer1")
lstm_layer1 = tf.nn.rnn_cell.DropoutWrapper(lstm_layer1, input_keep_prob=drop_out)
lstm_layer2 = tf.contrib.rnn.BasicLSTMCell(lstm_size2, state_is_tuple=True,name="LSTM_layer2")
lstm_layer2 = tf.nn.rnn_cell.DropoutWrapper(lstm_layer2, input_keep_prob=drop_out)

lstm = tf.nn.rnn_cell.MultiRNNCell([lstm_layer1,lstm_layer2], state_is_tuple=True)

batch_size=tf.shape(x_data)[0]
init_state = lstm.zero_state(batch_size, dtype=tf.float32)

# input data shape: 
output_rnn, out_state = tf.nn.dynamic_rnn(lstm, x_data, initial_state=init_state, dtype=tf.float32)

W_out = tf.get_variable("Wout",initializer=tf.random_normal([lstm_size2,1]))
b_out = tf.get_variable("b_out",initializer=tf.random_normal([1]))

# The LSTM output can be used to make next word predictions
W_repeated = tf.tile(tf.expand_dims(W_out,0), [batch_size,1,1])
out = tf.matmul(output_rnn, W_repeated)+b_out
out = tf.squeeze(out)


loss = tf.losses.mean_squared_error(y_real,out)
tf.summary.scalar('loss', loss)


#train_op = tf.train.AdamOptimizer(learning_rate=0.0002).minimize(loss)
optimizer = tf.train.AdamOptimizer(learning_rate=0.0002)
gvs = optimizer.compute_gradients(loss)
capped_gvs = [(tf.clip_by_value(grad, -1., 1.), var) for grad, var in gvs]
train_op = optimizer.apply_gradients(capped_gvs)

sess=tf.Session()
sess.run(tf.global_variables_initializer())

merged = tf.summary.merge_all()
train_writer = tf.summary.FileWriter ('./tb/train', sess.graph)
test_writer = tf.summary.FileWriter('./tb/test')


In [56]:
o = sess.run([out], feed_dict={x_data: train_x, 
                                      y_real:train_y})

print "The estimated output without training is:"
print np.squeeze(o)
print "But it should be:"
print train_y

The estimated output without training is:
[[-0.130519   -0.130519   -0.130519   -0.130519   -0.130519   -0.130519
  -0.130519   -0.130519   -0.130519   -1.5461134  -0.5214882  -0.2466977
  -0.25798646 -0.37975407  0.36350232]
 [-0.130519   -0.130519   -0.130519   -0.130519   -0.130519   -0.130519
  -0.130519   -0.130519   -0.130519   -0.130519   -0.130519   -0.130519
  -0.130519   -0.130519   -0.130519  ]
 [-0.130519   -0.130519   -0.99822617 -0.91869736 -1.2863333  -0.939237
  -0.9582306  -0.04468045 -0.3773907  -0.03603727  0.06230752  0.02335078
  -0.05038876  0.007392    0.08311416]
 [-0.130519   -0.130519   -0.130519   -0.130519   -0.130519   -0.130519
  -0.130519   -0.25780064 -0.46879348 -0.8717269  -0.94313014 -1.142331
  -0.7179986  -2.4164078  -1.0819685 ]]
But it should be:
[[ 43.  27.  74.  47.  21.  53.  70.  59. 102. 107.  76.  28.  75. 110.
   64.]
 [ 29.  37. 109.  67.  66. 103.  71.  85.  70.  62.  40.  56.  75.  47.
   86.]
 [ 23.  31.  76.  38.  63.  32.  27.  59. 10

In [62]:
max_epocs=80000
for i in xrange(max_epocs):
    myloss,summary,_ = sess.run([loss,merged,train_op], 
               feed_dict={x_data: train_x, y_real:train_y})  

    if i%500 == 0:        
        train_writer.add_summary(summary, i)
        myloss,summary = sess.run([loss,merged], 
               feed_dict={x_data: test_x, y_real:test_y})
        test_writer.add_summary(summary, i)
        print myloss

4778.294
4405.5664
4159.7725
4081.4028
3994.9119
3925.9688
3850.725
3785.6375
3713.281
3648.4714
3581.3223
3517.306
3455.0757
3391.6135
3330.9795
3266.9792
3205.8545
3145.659
3087.3726
3027.4517
2969.2905
2913.0447
2855.6987
2799.8145
2749.921
2690.305
2636.469
2583.4084
2531.5615
2479.995
2428.6833
2378.439
2328.9639
2280.158
2232.058
2184.6362
2138.1343
2091.4287
2046.6321
2002.0768
1958.2598
1915.0071
1872.5153
1830.7249
1789.6393
1749.208
1709.5464
1670.5476
1632.2944
1595.666
1557.7493
1521.5477
1486.0449
1451.2441
1417.142
1383.7499
1351.0349
1319.0277
1287.7196
1257.108
1227.1941
1199.0469
1169.4629
1141.6438
1114.5244
1088.1017
1062.3389
1037.3096
1013.0031
989.322
966.38446
941.85156
922.56976
901.712
881.5526
862.12866
843.3357
825.27655
807.85443
775.904
775.2696
760.0041
745.3347
727.0732
718.3506
705.8587
690.3069
682.9435
672.5339
663.0564
654.102
645.4724
653.25366
627.6974
625.2454
619.7798
615.0358
610.9784
589.28644
604.93835
588.24365
602.9716
601.25104
553.0942
585.

In [63]:
o = sess.run([out], feed_dict={x_data: test_x, 
                                      y_real:test_y})

print "The estimated output without training is:"
print np.squeeze(o)
print "But it should be:"
print train_y

The estimated output without training is:
[[33.481018 52.63614  68.95719  73.23729  73.48899  74.05496  74.23234
  74.25668  74.2544   74.27411  74.284355 74.285095 74.28507  74.28501
  74.28517 ]
 [21.609846 48.243286 69.012535 71.15938  73.76045  73.774704 74.12818
  74.19079  74.25257  74.253136 74.25452  74.258896 74.25892  74.26134
  74.27659 ]
 [31.201553 57.321785 60.84645  71.67826  71.98312  73.39107  73.537544
  74.07591  74.24061  74.267075 74.28226  74.28444  74.28578  74.28595
  74.28598 ]]
But it should be:
[[ 43.  27.  74.  47.  21.  53.  70.  59. 102. 107.  76.  28.  75. 110.
   64.]
 [ 29.  37. 109.  67.  66. 103.  71.  85.  70.  62.  40.  56.  75.  47.
   86.]
 [ 23.  31.  76.  38.  63.  32.  27.  59. 108.  82.  97.  85.  44.  81.
  112.]
 [ 38.  31.  76. 107. 122.  97.  62.  54.  99.  90.  70.  56.  78.  82.
  116.]]


In [17]:
train_x = np.array([[[1], [2], [5], [6]],
          [[5], [7], [7], [8]],
          [[3], [4], [5], [7]]])

train_x = np.array([[[1], [2], [5], [6]],
          [[5], [7], [7], [8]],
          [[3], [4], [5], [7]],
          [[2], [3], [7], [8]]])

train_y = np.array([[1, 3, 7, 11],
           [5, 12, 14, 15],
           [3, 7, 9, 12],
           [2, 5, 10 ,15]])

test_x = np.array([[[1], [2], [3], [4]],
          [[4], [5], [6], [7]]])

In [3]:
time_steps = 4
num_features = 1
lstm_size=10

In [18]:
tf.reset_default_graph()


batch_step = tf.placeholder(tf.float32, [None, num_features],"x_train")
y_real = tf.placeholder(tf.float32, [None, num_features])

batch_size = tf.shape(batch_step)[0]
lstm = tf.contrib.rnn.BasicLSTMCell(lstm_size, state_is_tuple=True,name="LSTM_cell")
# Initial state of the LSTM memory.
#init_state = state = lstm.zero_state(batch_size,tf.float32)
#c_in=tf.zeros((batch_size, lstm_size), np.float32,name="c_in")
#h_in=tf.zeros((batch_size, lstm_size),np.float32,name="h_in")
c_in=tf.placeholder(tf.float32, [None, lstm_size],name="c_in")
h_in=tf.placeholder(tf.float32, [None, lstm_size],name="h_in")
                    
init_state = tf.contrib.rnn.LSTMStateTuple( c=c_in, h=h_in)
#reset_state=tf.identity_n(init_state)


loss = 0.0
# The value of state is updated after processing each batch of words.
output_rnn, out_state = lstm(batch_step, init_state)


W_out = tf.get_variable("Wout",initializer=tf.random_normal([lstm_size,1]))
b_out = tf.get_variable("b_out",initializer=tf.random_normal([1]))


# The LSTM output can be used to make next word predictions
out = tf.matmul(output_rnn, W_out) + b_out

loss = tf.losses.mean_squared_error(y_real,out)
train_op = tf.train.AdamOptimizer().minimize(loss)

sess=tf.Session()
sess.run(tf.global_variables_initializer())

np_c = np.zeros((train_x.shape[0], lstm_size),np.float32)
np_h = np.zeros((train_x.shape[0], lstm_size),np.float32)

print sess.run([out,loss,train_op], 
               feed_dict={batch_step: train_x[:,0,:], 
                          y_real:train_y[:,0].reshape(-1,1),
                          c_in:np_c, h_in:np_h
                         })
train_writer = tf.summary.FileWriter('./graphtf',sess.graph)


[array([[-0.950649  ],
       [-0.6088793 ],
       [-0.75499594],
       [-0.84744596]], dtype=float32), 14.368125, None]


In [21]:
max_epocs=1000
for j in xrange(max_epocs):
    np_c = np.zeros((train_x.shape[0], lstm_size),np.float32)
    np_h = np.zeros((train_x.shape[0], lstm_size),np.float32)
    for i in xrange(4):        
        new_state,myloss,_ = sess.run([out_state,loss,train_op], 
               feed_dict={batch_step: train_x[:,i,:], 
                          y_real:train_y[:,i].reshape(-1,1),
                          c_in:np_c, h_in:np_h
                         })        
        np_c=new_state.c
        np_h=new_state.h
    if j%100 == 0:
        print myloss

0.49185872
0.40784678
0.34643236
0.30182305
0.27053022
0.24956086
0.23522538
0.2237002
0.21229109
0.19987653


In [23]:
np_c = np.zeros((test_x.shape[0], lstm_size),np.float32)
np_h = np.zeros((test_x.shape[0], lstm_size),np.float32)

for i in xrange(4):
    out_val,new_state = sess.run([out,out_state], feed_dict={batch_step: test_x[:,i,:],c_in:np_c, h_in:np_h})
    np_c=new_state.c
    np_h=new_state.h
    print out_val
    

[[0.9709455]
 [4.0639324]]
[[2.9082494]
 [9.049345 ]]
[[ 4.6729946]
 [11.843623 ]]
[[ 6.1187854]
 [12.876646 ]]


In [428]:
test_x

array([[[1],
        [2],
        [3],
        [4]],

       [[4],
        [5],
        [6],
        [7]]])

In [ ]:
[[ 1.6971655  2.9445994  4.9434905  7.257107 ]
 [ 4.436798   9.061197  11.678692  12.575489 ]]


https://medium.com/@erikhallstrm/hello-world-rnn-83cd7105b767

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.contrib import rnn

In [37]:
class SeriesPredictor:
    def __init__(self, input_dim, seq_size, hidden_dim=10):
        
        self.input_dim=input_dim
        self.seq_size=seq_size
        self.hidden_dim=hidden_dim
        
        self.W_out = tf.Variable(tf.random_normal([hidden_dim,1]),name='W_out')
        self.b_out = tf.Variable(tf.random_normal([1]),name='b_out')
        self.x = tf.placeholder(tf.float32, [None, seq_size, input_dim])
        self.y = tf.placeholder(tf.float32, [None, seq_size])
        
        
        self.cost = tf.reduce_mean(tf.square(self.model()-self.y))
        self.train_op = tf.train.AdamOptimizer().minimize(self.cost)
        
        self.saver = tf.train.Saver()
        
        
    def model(self):
        """
        :param x: inputs of size [T, batch_size, input_size]
        :param W: matrix of fully-connected output layer weights
        :param b: vector of fully-connected output layer biases
        """
        cell = rnn.BasicLSTMCell(self.hidden_dim)
        outputs, states = tf.nn.dynamic_rnn(cell, self.x, dtype=tf.float32)
        num_examples = tf.shape(self.x)[0]
        W_repeated = tf.tile(tf.expand_dims(self.W_out,0), [num_examples,1,1])
        out = tf.matmul(outputs, W_repeated)+self.b_out
        out = tf.squeeze(out)
        return out
    
    def train(self, train_x, train_y):
        with tf.Session() as sess:
            tf.get_variable_scope().reuse_variables()
            sess.run(tf.global_variables_initializer())
            for i in range(1000):
                _, mse = sess.run([self.train_op, self.cost], feed_dict={self.x: train_x, self.y: train_y})
                if i% 100 == 0:
                    print(i,mse)
            save_path = self.saver.save(sess,'./model.ckpt')
            print('Model saved to {}'.format(save_path))
                
        
    def test(self,test_x):
        with tf.Session() as sess:
            tf.get_variable_scope().reuse_variables()
            self.saver.restore(sess, './model.ckpt')
            output = sess.run(self.model(), feed_dict={self.x: test_x})
            print(output)

    
        

In [10]:
class SeriesPredictor:
    def __init__(self, input_dim, seq_size, hidden_dim=10):
        
        self.input_dim=input_dim
        self.seq_size=seq_size
        self.hidden_dim=hidden_dim
        
        self.W_out = tf.get_variable("Wout",initializer=tf.random_normal([hidden_dim,1]))
        self.b_out = tf.get_variable("b_out",initializer=tf.random_normal([1]))
        self.x = tf.placeholder(tf.float32, [None, seq_size, input_dim])
        self.y = tf.placeholder(tf.float32, [None, seq_size])
        
        self.mymodel = self.model()
        self.cost = tf.reduce_mean(tf.square(self.mymodel-self.y))
        self.train_op = tf.train.AdamOptimizer().minimize(self.cost)
        
        self.saver = tf.train.Saver()
        
    def model(self):
        """
        :param x: inputs of size [T, batch_size, input_size]
        :param W: matrix of fully-connected output layer weights
        :param b: vector of fully-connected output layer biases
        """
        cell = rnn.BasicLSTMCell(self.hidden_dim)
        outputs, states = tf.nn.dynamic_rnn(cell, self.x, dtype=tf.float32)
        num_examples = tf.shape(self.x)[0]
        W_repeated = tf.tile(tf.expand_dims(self.W_out,0), [num_examples,1,1])
        out = tf.matmul(outputs, W_repeated)+self.b_out
        out = tf.squeeze(out)
        return out
    
    def train(self, train_x, train_y):
        sess = tf.Session()
        sess.run(tf.global_variables_initializer())
        for i in range(1000):
            _, mse = sess.run([self.train_op, self.cost], feed_dict={self.x: train_x, self.y: train_y})
            if i% 100 == 0:
                print(i,mse)
        return sess
                
        
    def test(self,sess,test_x):        
        output = sess.run(self.mymodel, feed_dict={self.x: test_x})
        print(output)

    
        

In [11]:
tf.reset_default_graph()
predictor = SeriesPredictor(input_dim=1, seq_size=4, hidden_dim=10)
train_x = [[[1], [2], [5], [6]],
          [[5], [7], [7], [8]],
          [[3], [4], [5], [7]]]
train_y = [[1, 3, 7, 11],
           [5, 12, 14, 15],
           [3, 7, 9, 12]]
sess=predictor.train(train_x, train_y)

test_x = [[[1], [2], [3], [4]],
          [[4], [5], [6], [7]]]

predictor.test(sess,test_x)

(0, 104.54908)
(100, 49.596928)
(200, 13.441304)
(300, 4.84034)
(400, 3.223334)
(500, 2.582983)
(600, 1.9891154)
(700, 1.4041783)
(800, 1.0117636)
(900, 0.73919386)
[[ 0.69609344  2.6687462   5.052478    6.9160995 ]
 [ 4.0849714   9.2390785  11.849617   12.85392   ]]


In [17]:
train_x[0][0]

[[1], [2], [5], [6]]